version: "3.1"

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: test_db
    volumes:
        - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
        - db_network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks: 
        - db_network
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
        PGADMIN_LISTEN_ADDRESS: 0.0.0.0
        PGADMIN_LISTEN_PORT: 8080
    ports:
      - "5050:8080"
    links:
        - db
    volumes:
        - ./pgadminData/:/var/lib/pgadmin
networks:
  db_network: {}